### ISSUE TITLE
[BUG] White screen on Mirador Paged Content context config page

### ISSUE THREAD

**Issue by alxp** [Islandora-Devops/islandora-starter-site#44]
### Steps to reproduce:

1. Download and nable Islandora Mirador
2. Go to http://localhost:8000/admin/structure/context/paged_content_mirador

### Error message

```bash
[Thu Jan 19 07:56:24.999203 2023] [php7:notice] [pid 32160] [client 10.0.2.2:56368] TypeError: Argument 1 passed to Drupal\\Core\\Entity\\EntityRepository::getTranslationFromContext() must implement interface Drupal\\Core\\Entity\\EntityInterface, null given, called in /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Element/EntityAutocomplete.php on line 373 in /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityRepository.php on line 93 #0 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Element/EntityAutocomplete.php(373): Drupal\\Core\\Entity\\EntityRepository->getTranslationFromContext(NULL)\n#1 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Element/EntityAutocomplete.php(119): Drupal\\Core\\Entity\\Element\\EntityAutocomplete::getEntityLabels(Array)\n#2 [internal function]: Drupal\\Core\\Entity\\Element\\EntityAutocomplete::valueCallback(Array, false, Object(Drupal\\Core\\Form\\FormState))\n#3 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1285): call_user_func_array(Array, Array)\n#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1003): Drupal\\Core\\Form\\FormBuilder->handleInputElement('context_edit_fo...', Array, Object(Drupal\\Core\\Form\\FormState))\n#5 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1073): Drupal\\Core\\Form\\FormBuilder->doBuildForm('context_edit_fo...', Array, Object(Drupal\\Core\\Form\\FormState))\n#6 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1073): Drupal\\Core\\Form\\FormBuilder->doBuildForm('context_edit_fo...', Array, Object(Drupal\\Core\\Form\\FormState))\n#7 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1073): Drupal\\Core\\Form\\FormBuilder->doBuildForm('context_edit_fo...', Array, Object(Drupal\\Core\\Form\\FormState))\n#8 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(1073): Drupal\\Core\\Form\\FormBuilder->doBuildForm('context_edit_fo...', Array, Object(Drupal\\Core\\Form\\FormState))\n#9 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(577): Drupal\\Core\\Form\\FormBuilder->doBuildForm('context_edit_fo...', Array, Object(Drupal\\Core\\Form\\FormState))\n#10 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(323): Drupal\\Core\\Form\\FormBuilder->processForm('context_edit_fo...', Array, Object(Drupal\\Core\\Form\\FormState))\n#11 /var/www/html/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\\Core\\Form\\FormBuilder->buildForm(Object(Drupal\\context_ui\\Form\\ContextEditForm), Object(Drupal\\Core\\Form\\FormState))\n#12 [internal function]: Drupal\\Core\\Controller\\FormController->getContentResult(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\RouteMatch))\n#13 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)\n#14 /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(580): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#15 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#16 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)\n#17 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(169): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber->Drupal\\Core\\EventSubscriber\\{closure}()\n#18 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#19 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#20 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#21 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#22 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#23 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#24 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#25 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#26 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(713): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#27 /var/www/html/drupal/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#28 {main}, referer: http://localhost:8000/admin/structure/context
root@islandora8:/var/www/html/drupal/web/sites/default#  

```

Unsure yet if this is only on Playbook and if it's specifically related to the Mirador context.

**Comment by alxp** [comment]
I rebuilt my image and the error is not occurring any more so I think you are right.

Closing.
